# Copyright (c) 2021-2023 Koji Hasegawa.
# This software is released under the MIT License.

name: Lint workflow files

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/**
  pull_request:
    types: [ opened, synchronize, reopened ]  # Same as default
    paths:
      - .github/workflows/**

permissions: write-all
jobs:
  actionlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint workflow files
        shell: bash
        run: |
          bash <(curl -LsS --retry 2 https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,job,pullRequest
          mention: here
          if_mention: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: failure() && github.repository_owner == 'DeNA' # Skip public fork, because can not read secrets.
