# Copyright (c) 2023 DeNA Co., Ltd.
# This software is released under the MIT License.

name: PR Labeler

on:
  pull_request_target:
    types: [ opened ]
    # Do NOT check out, build, or run untrusted code from the pull request with this event.

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-labeler:
    runs-on: ubuntu-latest

    steps:
      - uses: TimonVS/pr-labeler-action@f9c084306ce8b3f488a8f3ee1ccedc6da131d1af # v5
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
